### PR TITLE
Default jacoco version and `includeNoLocationClasses` flag

### PR DESCRIPTION
**Pull request by f3ist**
Relates to #51. 2 commits here so you can cherry pick if you want

### CODE REVIEW

**Comment by f3ist** [comment]
I tested it out locally and updated the tests, which pass. It seems to work fine by changing it to null.

**Comment by vanniktech** [comment]
Yeah it might work out for you but I still want the default version to be what it was before since others might rely on that particular version (they changed their format with a specific version which might already be the default version of gradle)

**Comment by f3ist** [comment]
That makes sense. I did commit it in 2 commits, so you can cherry pick the
jacoco flag for Android.

You could save the other commit for v1.0 or something.

**Comment by vanniktech** [comment]
I thought of something like #55

**Comment by f3ist** [comment]
Looks good and simple. I believe the flag is only available in gradle 2.13+ though

**Comment by vanniktech** [comment]
Cool then I'll close this. Thanks, SNAPSHOT should be up soon

**Pull request closed without merging**
