### PR TITLE
Update libraries to latest.

### PR DESCRIPTION
**Pull request by vanniktech**

### CODE REVIEW

**Comment by vanniktech** [comment]
@passsy can you help here it's failing now with:

```
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'test'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:94)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:89)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:70)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$100(LifecycleProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$ConfigureProject.run(LifecycleProjectEvaluator.java:110)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:656)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:135)
	at com.vanniktech.android.junit.jacoco.GenerationPluginSpec.android - all tasks created(GenerationPluginSpec.groovy:52)
Caused by: java.lang.RuntimeException: Cannot read packageName from /private/var/folders/dc/f2hgg3nj2311j_m4lm75lgmr0000gn/T/gradle8376341198848839607projectDir/src/main/AndroidManifest.xml
	at com.android.builder.core.VariantConfiguration.getPackageFromManifest(VariantConfiguration.java:927)
	at com.android.builder.core.VariantConfiguration.getOriginalApplicationId(VariantConfiguration.java:679)
	at com.android.build.gradle.tasks.ProcessAndroidResources$ConfigAction.execute(ProcessAndroidResources.java:849)
	at com.android.build.gradle.tasks.ProcessAndroidResources$ConfigAction.execute(ProcessAndroidResources.java:714)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:148)
	at com.android.build.gradle.internal.TaskContainerAdaptor.create(TaskContainerAdaptor.java:58)
	at com.android.build.gradle.internal.scope.AndroidTaskRegistry.create(AndroidTaskRegistry.java:45)
	at com.android.build.gradle.internal.scope.AndroidTaskRegistry.create(AndroidTaskRegistry.java:87)
	at com.android.build.gradle.internal.TaskManager.createProcessResTask(TaskManager.java:1198)
	at com.android.build.gradle.internal.TaskManager.createApkProcessResTask(TaskManager.java:1143)
	at com.android.build.gradle.internal.ApplicationTaskManager.lambda$createTasksForVariantScope$6(ApplicationTaskManager.java:164)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
	at com.android.build.gradle.internal.ApplicationTaskManager.createTasksForVariantScope(ApplicationTaskManager.java:158)
	at com.android.build.gradle.internal.VariantManager.createTasksForVariantData(VariantManager.java:545)
	at com.android.build.gradle.internal.VariantManager.lambda$createAndroidTasks$1(VariantManager.java:355)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
	at com.android.build.gradle.internal.VariantManager.createAndroidTasks(VariantManager.java:351)
	at com.android.build.gradle.BasePlugin.lambda$createAndroidTasks$5(BasePlugin.java:641)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:636)
	at com.android.build.gradle.BasePlugin.lambda$null$3(BasePlugin.java:555)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
	at com.android.build.gradle.BasePlugin.lambda$createTasks$4(BasePlugin.java:551)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:76)
	... 11 more
```

is it as easy as adding the package name somewhere?

**Comment by passsy** [comment]
I can reproduce it. I guess the new gradle plugin does not only require an `applicationId` but also a valid `src/main/AndroidManifest.xml` with a `packageName` attribute.
I'd try to add this file with `withProjectDir(dir)` but I don't know how to create files for tests.
 
```groovy
    project = ProjectBuilder.builder()
      .withProjectDir(testProjectDir)
      .build()
```

Btw I'm only able to run the tests from command line. IntelliJ gives me this error: 
```
Caused by: java.lang.NullPointerException: Cannot invoke method toURI() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at com.vanniktech.android.junit.jacoco.GenerationPluginSpec.<clinit>(GenerationPluginSpec.groovy:14)
	... 21 more
```

**Comment by vanniktech** [comment]
Do you get the error all the time or just when you try to add your workaround? I have not encountered the `Caused by: java.lang.NullPointerException: Cannot invoke method toURI() on null object`.

**Comment by passsy** [comment]
I get this error without local changes. I tried jdk8 and 9. Tried removing the leading "/". Didn't help

**Comment by vanniktech** [comment]
Interesting, maybe updating to Gradle 4.4 helps here? Also are you running on Windows? I dont' get this error when using my mac.

**Comment by passsy** [comment]
Reimporting the project in IntelliJ solved the resource loading problem. Thanks @jannisveerkamp

**Pull request merged**
