### PR TITLE
Restore flavor iterations

### PR DESCRIPTION
**Pull request by outlying**
This should address issue #28

### CODE REVIEW

**Comment by vanniktech** [comment]
Could you add some test cases there as well?

**Comment by outlying** [comment]
Sure, I will do that

czw., 7.07.2016 o 15:30 użytkownik Niklas Baudy <notifications@github.com>
napisał:

**Comment by outlying** [comment]
Sure, I will do that

**Comment by outlying** [comment]
I reorganized tests a little bit, removed setUp section since some of the tests now require Android project with flavors but others don't. Also, it was pointless to create Java project object for pure Android project test.

Right now projects are created as needed by the test methods.

**Comment by vanniktech** [comment]
@outlying alright thanks a lot I'll take a look at this later

**Comment by vanniktech** [comment]
@outlying thanks a lot for now you can use the SNAPSHOT I'll try to cut a release in the next few days.

**Pull request merged**
