### PR TITLE
Fix StackOverflowError with Gradle 5.0 regarding FileCollection

### PR DESCRIPTION
**Pull request by Laimiux**
Fixing issue discussed in: https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/issues/136

### CODE REVIEW

**Comment by wiyarmir** [comment]
Any plans to cut a release including this fix? 😄 Thanks!

**Comment by vanniktech** [comment]
According to https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/issues/139#issuecomment-473673651 not all cases have been fixed and I haven't had time to look into it yet.

**Comment by wiyarmir** [comment]
Oh! I see. Let me know if you want help with anything 🙂

**Comment by vanniktech** [comment]
If you can find the issue and create a PR with a fix I'd be super gradeful.

**Pull request merged**
