### PR TITLE
Add the new path for Java class files in newer Android Gradle Plugin …

### PR DESCRIPTION
**Pull request by vRallev**
…versions. Without this additional path the coverage for Java files is missing.

### CODE REVIEW

**Comment by vRallev** [comment]
I don't know when this broke (maybe AGP 3.2), but we don't have a coverage for our java files at the moment and get wrong result because of that.

**Comment by vRallev** [comment]
This fix is critical for us. May I ask for a release soon after it has been merged? I'd hate to setup a fork.

**Comment by vanniktech** [comment]
Released as 0.12.0, thanks for fixing it Ralf!

**Comment by vRallev** [comment]
Thank you for the quick release. I really appreciate it!

**Pull request merged**
